/**
 * VEIL System Types (Facet-Based Architecture)
 *
 * Shared interfaces describing the VEIL (Virtual Environment Interface Language)
 * state, facets, and component APIs for AXON modules.
 */

import type { ISpaceEvent } from './events';
import { IComponent } from './core';

// ============================================
// ASPECTS
// ============================================

/** Facets that surface readable content */
export interface ContentAspect {
  content: string;
}

/** Facets that expose structured state */
export interface StateAspect<T = Record<string, any>> {
  state: T;
}

/** Facets generated by an agent */
export interface AgentGeneratedAspect {
  agentId: string;
  agentName?: string;
}

/** Facets that expire when the frame completes */
export interface EphemeralAspect {
  ephemeral: true;
}

/** Facets scoped to specific logical groupings */
export interface ScopedAspect {
  scopes: string[];
}

/** Facets associated with a stream */
export interface StreamAspect {
  streamId: string;
  streamType?: string;
}

/** Facets that reference other facets */
export interface TargetedAspect {
  targetFacetIds: string[];
}

/** Base fields shared by all facets */
export interface BaseFacet {
  id: string;
  type: string;
}

// ============================================
// AGENT COMMUNICATION FACETS
// ============================================

export type SpeechFacet = BaseFacet & ContentAspect & AgentGeneratedAspect & StreamAspect & {
  type: 'speech';
};

export type ThoughtFacet = BaseFacet & ContentAspect & AgentGeneratedAspect & StreamAspect & {
  type: 'thought';
};

export type ActionFacet = BaseFacet & ContentAspect & StateAspect<{
  toolName: string;
  parameters: Record<string, any>;
}> & AgentGeneratedAspect & StreamAspect & {
  type: 'action';
};

// ============================================
// CORE CONTENT FACETS
// ============================================

export type EventFacet = BaseFacet & ContentAspect & StateAspect<{
  source: string;
  eventType: string;
  metadata?: any;
}> & StreamAspect & {
  type: 'event';
};

export type StateFacet = BaseFacet & ContentAspect & StateAspect & ScopedAspect & {
  type: 'state';
  entityType: 'component' | 'element' | 'agent';
  entityId: string;
};

export type AmbientFacet = BaseFacet & ContentAspect & StreamAspect & {
  type: 'ambient';
};

export type EphemeralFacet = BaseFacet & ContentAspect & EphemeralAspect & {
  type: 'ephemeral';
};

// ============================================
// CONFIGURATION & INTERNAL FACETS
// ============================================

export type ConfigFacet = BaseFacet & StateAspect & {
  type: 'config';
  configType: string;
};

export type InternalStateFacet = BaseFacet & StateAspect & {
  type: 'internal-state';
  componentId: string;
};

// ============================================
// META / SYSTEM FACETS
// ============================================

export type StateChangeFacet = BaseFacet & TargetedAspect & StateAspect<{
  changes: Record<string, { old: any; new: any }>;
}> & EphemeralAspect & {
  type: 'state-change';
};

export type ScopeChangeFacet = BaseFacet & StateAspect<{
  operation: 'add' | 'remove';
  scopeId: string;
  scopeData?: any;
}> & EphemeralAspect & {
  type: 'scope-change';
};

export type StreamChangeFacet = BaseFacet & StateAspect<{
  operation: 'add' | 'remove' | 'activate';
  streamId: string;
  streamType?: string;
}> & EphemeralAspect & {
  type: 'stream-change';
};

export type AgentLifecycleFacet = BaseFacet & StateAspect<{
  operation: 'register' | 'deregister' | 'activate' | 'deactivate';
  agentId: string;
  agentInfo?: any;
}> & EphemeralAspect & {
  type: 'agent-lifecycle';
};

export type AgentActivationFacet = BaseFacet & StateAspect<{
  reason: string;
  priority: 'low' | 'normal' | 'high' | 'critical';
  sourceAgentId?: string;
}> & EphemeralAspect & {
  type: 'agent-activation';
};

export type RenderedContextFacet = BaseFacet & ContentAspect & StateAspect<{
  activationId: string;
  tokenCount: number;
  compressionRatio?: number;
}> & EphemeralAspect & {
  type: 'rendered-context';
};

export type ActionDefinitionFacet = BaseFacet & StateAspect<{
  actionName: string;
  parameters: string[];
  description: string;
  handler: string;
}> & {
  type: 'action-definition';
};

// ============================================
// FACET UNIONS & HELPERS
// ============================================

export type ContentFacet =
  | SpeechFacet
  | ThoughtFacet
  | ActionFacet
  | EventFacet
  | StateFacet
  | AmbientFacet
  | EphemeralFacet
  | RenderedContextFacet;

export type Facet =
  | ContentFacet
  | ConfigFacet
  | InternalStateFacet
  | StateChangeFacet
  | ScopeChangeFacet
  | StreamChangeFacet
  | AgentLifecycleFacet
  | AgentActivationFacet
  | ActionDefinitionFacet;

export type FacetType = Facet['type'];

export function hasContentAspect(facet: Facet): facet is Facet & ContentAspect {
  return 'content' in facet;
}

export function hasStateAspect(facet: Facet): facet is Facet & StateAspect {
  return 'state' in facet;
}

export function hasAgentGeneratedAspect(
  facet: Facet
): facet is Facet & AgentGeneratedAspect {
  return 'agentId' in facet;
}

export function hasEphemeralAspect(facet: Facet): facet is Facet & EphemeralAspect {
  return 'ephemeral' in facet && (facet as EphemeralAspect).ephemeral === true;
}

export function hasStreamAspect(facet: Facet): facet is Facet & StreamAspect {
  return 'streamId' in facet;
}

export function hasScopedAspect(facet: Facet): facet is Facet & ScopedAspect {
  return 'scopes' in facet;
}

export function hasTargetedAspect(facet: Facet): facet is Facet & TargetedAspect {
  return 'targetFacetIds' in facet;
}

// ============================================
// VEIL DELTAS & STATE
// ============================================

export type VEILDelta =
  | { type: 'addFacet'; facet: Facet }
  | { type: 'changeFacet'; id: string; changes: Partial<Facet> }
  | { type: 'removeFacet'; id: string };

export interface StreamInfo {
  id: string;
  name?: string;
  metadata?: Record<string, any>;
}

export interface StreamRef {
  streamId: string;
  streamType: string;
  metadata?: Record<string, any>;
}

export interface AgentInfo {
  id: string;
  name: string;
  type?: string;
  capabilities?: string[];
  metadata?: Record<string, any>;
  createdAt: string;
  lastActiveAt?: string;
}

export interface FrameTransition {
  sequence: number;
  timestamp: string;
  elementOps: any[];
  componentOps: any[];
  componentChanges: any[];
  veilOps: VEILDelta[];
  extensions?: Record<string, any>;
}

export interface IVEILFrame {
  sequence: number;
  timestamp: string;
  uuid?: string;
  activeStream?: StreamRef;
  events: ISpaceEvent[];
  deltas: VEILDelta[];
  transition: FrameTransition;
}

export interface IVEILState {
  facets: Map<string, Facet>;
  scopes: Set<string>;
  streams: Map<string, StreamInfo>;
  agents: Map<string, AgentInfo>;
  currentStream?: StreamRef;
  currentAgent?: string;
  frameHistory: IVEILFrame[];
  currentSequence: number;
  removals: Map<string, 'hide' | 'delete'>;
}

// ============================================
// COMPONENT INTERFACES
// ============================================

export interface FacetCreationOptions {
  id: string;
  type: FacetType;
  content?: string;
  displayName?: string;
  scope?: string[];
  attributes?: Record<string, any>;
  attributeRenderers?: Record<string, (value: any, oldValue?: any) => string | null>;
  transitionRenderers?: Record<string, (newValue: any, oldValue: any) => string | null>;
  children?: Facet[];
  streamId?: string;
  streamType?: string;
  agentId?: string;
  agentName?: string;
  entityType?: StateFacet['entityType'];
  entityId?: string;
}

export interface IVEILComponent extends IComponent {
  addOperation(delta: VEILDelta): void;
  trackPropertyChange(propertyName: string, oldValue: unknown, newValue: unknown): void;
  setTrackedProperty(key: string, value: unknown): void;
  addFacet(facet: FacetCreationOptions): void;
  updateState(
    id: string,
    changes: {
      content?: string;
      state?: Record<string, any>;
      attributes?: Record<string, any>;
    },
    updateMode?: 'full' | 'attributesOnly'
  ): void;
}

export interface IInteractiveComponent extends IVEILComponent {
  registerAction(name: string, handler: (params?: any) => Promise<void>): void;
  addAmbient(
    content: string,
    idOrAttributes?: string | Record<string, any>,
    attributes?: Record<string, any>
  ): void;
  addState(id: string, content: string, attributes?: Record<string, any>): void;
  changeState(id: string, changes: { content?: string; attributes?: Record<string, any> }): void;
  addEvent(
    content: string,
    eventType?: string,
    idOrAttributes?: string | Record<string, any>,
    attributes?: Record<string, any>
  ): void;
  inFrame(): boolean;
  requireFrame(): void;
  getVeilState(): unknown;
  deferToNextFrame(operation: () => void): void;
}
